#!/usr/bin/env bash

loadkeys ru
setfont cyr-sun16
timedatectl set-ntp true

echo -e "\e[96mНачало установки.\e[0m"


#--------------- Подготовка разделов ----------------
mkfs.btrfs -f $ROOT_PART
mount --mkdir -o subvolid=5 $ROOT_PART /mnt/btrfs-top
btrfs subvolume create /mnt/btrfs-top/@
btrfs subvolume create /mnt/btrfs-top/@swap
btrfs subvolume create /mnt/btrfs-top/@var
umount /mnt/btrfs-top
rmdir /mnt/btrfs-top
mount -o subvol=@,compress=zstd,noatime $ROOT_PART /mnt

mount --mkdir -o subvol=@swap,compress=no,noatime $ROOT_PART /mnt/.swap
btrfs filesystem mkswapfile --size 7629m --uuid clear /mnt/.swap/swapfile # 8 GB = 7629 MiB
mkswap /mnt/.swap/swapfile
swapon /mnt/.swap/swapfile

mount --mkdir -o subvol=@var,compress=zstd,noatime $ROOT_PART /mnt/var
chattr +C /mnt/var # disable Copy-on-Write for /var; lsattr -d /var

mkfs.fat -F 16 $EFI_PART
mount --mkdir $EFI_PART /mnt/boot/efi

mount --mkdir $HOME_PART /mnt/home
tune2fs -m 0 $HOME_PART #remove root reserved space on /home

# Переместить каталоги из /mnt/home в /mnt/home/old
mkdir -p /mnt/home/old-tmp
shopt -s nullglob
for d in /mnt/home/*/; do
  base="$(basename "${d%/}")"
  [ $d = /mnt/home/old-tmp/ ] && continue
  [ $d = /mnt/home/lost+found/ ] && continue
  mv $d /mnt/home/old-tmp/$base
done
mv /mnt/home/old-tmp /mnt/home/old


#--------------- Установка системы -------------------------
sed -i "s|Server = |#Server = |g" /etc/pacman.d/mirrorlist
echo 'Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch' >> /etc/pacman.d/mirrorlist
pacman -S --refresh

echo -e "\e[96mПеремещение файлов.\e[0m"
mv /targetfs/rootfs/etc /mnt/
mv /targetfs/rootfs/opt /mnt/
mv /targetfs/rootfs/root /mnt/
mv /targetfs/rootfs/usr /mnt/
mv /targetfs/rootfs/var/* /mnt/var
mv /targetfs/homefs/* /mnt/home

PACKAGES=$(sed 's/#.*//' /root/pacman-packages.conf | sed '/^[[:space:]]*$/d' | xargs)
pacstrap -K /mnt $PACKAGES


#--------------- Настройка разделов -----------------------
genfstab -U /mnt > /mnt/etc/fstab
echo "tmpfs                                     /tmp           tmpfs   defaults,noatime,mode=1777 0 0" >> /mnt/etc/fstab
echo "skyserver:/sky                            /sky           nfs     soft,intr,timeo=10,retry=3,_netdev,noatime,bg   0 0" >> /mnt/etc/fstab


#--------------- Настройка системы -------------------------
arch-chroot /mnt /root/install-on-system

rm -rf /mnt/usr/share/grub/themes/starfield
rm -f /mnt/root/install-on-system


#--------------- Завершение --------------------------------
swapoff /mnt/.swap/swapfile
umount -R /mnt/boot/efi
umount -R /mnt/home
umount -R /mnt

echo -e "\e[96mУстановка завершена. Перезагрузите систему.\e[0m"
