#!/usr/bin/env bash


DISK=/dev/sda
ROOT_PART=${DISK}1


loadkeys ru
setfont cyr-sun16

echo -e "\e[96mНачало установки на $DISK. Это уничтожит все данные на диске.\e[0m"

timedatectl set-ntp true


#--------------- Подготовка таблицы разделов ----------------
sgdisk --zap-all $DISK || true
parted --script $DISK mklabel msdos
parted --script $DISK mkpart primary ext4 0% 100%
parted --script $DISK set 1 boot on
partprobe $DISK

mkfs.ext4 $ROOT_PART
mount $ROOT_PART /mnt


#--------------- Установка системы -------------------------
rate-mirrors --entry-country=RU --allow-root arch | tee /etc/pacman.d/mirrorlist

mkdir -p /mnt/var/cache/pacman/pkg
mv pacman-cache/* /mnt/var/cache/pacman/pkg

PACKAGES=$(sed 's/#.*//' pacman-packages.conf | sed '/^[[:space:]]*$/d' | xargs)
pacstrap -K /mnt $PACKAGES

genfstab -U /mnt >> /mnt/etc/fstab


#--------------- Настройка системы -------------------------
cp /root/setup-config /mnt/root/setup-config
cp /root/setup /mnt/root/setup
cp /root/setup-user /mnt/root/setup-user
cp /root/user-prefs.dconf /mnt/root/user-prefs.dconf

mkdir -p /mnt/var/tmp/aur-cache
mv aur-cache/* /mnt/var/tmp/aur-cache

mkdir -p /mnt/usr/share/plank/themes
mv custom-cache/usr/share/themes/* /mnt/usr/share/themes/
mv custom-cache/usr/share/plank/themes/* /mnt/usr/share/plank/themes/
mv custom-cache/usr/share/icons/* /mnt/usr/share/icons/

arch-chroot /mnt /root/setup

rm -f /mnt/root/setup-config
rm -f /mnt/root/setup


#--------------- Завершение --------------------------------
umount -R /mnt

echo "Установка завершена. Перезагрузите систему."
