#!/usr/bin/env bash


DISK=/dev/sda
ROOT_PART=${DISK}1


loadkeys ru
setfont cyr-sun16

echo -e "\e[96mНачало установки на $DISK. Это уничтожит все данные на диске.\e[0m"

timedatectl set-ntp true


#--------------- Подготовка таблицы разделов ----------------
sgdisk --zap-all $DISK || true
parted --script $DISK mklabel msdos
parted --script $DISK mkpart primary ext4 0% 100%
parted --script $DISK set 1 boot on
partprobe $DISK

mkfs.ext4 $ROOT_PART
mount $ROOT_PART /mnt

tune2fs -m 1 $ROOT_PART # 1% reserved space on /


#--------------- Установка системы -------------------------
rate-mirrors --entry-country=RU --allow-root arch | tee /etc/pacman.d/mirrorlist

mkdir -p /mnt/var/cache/pacman/pkg
mv pacman-cache/* /mnt/var/cache/pacman/pkg

PACKAGES=$(sed 's/#.*//' pacman-packages.conf | sed '/^[[:space:]]*$/d' | xargs)
pacstrap -K /mnt $PACKAGES

genfstab -U /mnt >> /mnt/etc/fstab


#--------------- Настройка системы -------------------------
cp /root/install-on-system /mnt/root/install-on-system
cp /root/install-on-system.env /mnt/root/install-on-system.env
cp /root/install-on-user /mnt/root/install-on-user
cp /root/user-first-login /mnt/root/user-first-login
cp /root/user-prefs.dconf /mnt/root/user-prefs.dconf

mkdir -p /mnt/var/tmp/aur-cache
mv aur-cache/* /mnt/var/tmp/aur-cache

mkdir -p /mnt/usr/share/plank/themes
mv custom-cache/usr/share/themes/* /mnt/usr/share/themes/
mv custom-cache/usr/share/plank/themes/* /mnt/usr/share/plank/themes/
mv custom-cache/usr/share/icons/* /mnt/usr/share/icons/

arch-chroot /mnt /root/install-on-system

rm -f /mnt/root/install-on-system
rm -f /mnt/root/install-on-system.env


#--------------- Завершение --------------------------------
umount -R /mnt

echo "Установка завершена. Перезагрузите систему."
