#!/usr/bin/env bash


#--------------- Настройка -------------------------------------
source /root/install-on-system.env

USER_HOME=/home/$USERNAME

#chsh -s /bin/fish

# timezone and clock
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
hwclock --systohc

# locale
echo "en_US.UTF-8 UTF-8
ru_RU.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=ru_RU.UTF-8" > /etc/locale.conf

# console keymap
echo "KEYMAP=ru
FONT=cyr-sun16" > /etc/vconsole.conf

# hostname
echo "$HOSTNAME" > /etc/hostname
cat > /etc/hosts <<HOSTS
127.0.0.1   localhost
::1         localhost
127.0.1.1   $HOSTNAME.localdomain $HOSTNAME
HOSTS

# образ initramfs
mkinitcpio -P

# root password
echo "root:$USER_PASSWORD" | chpasswd

# create user
useradd --create-home --user-group --groups wheel $USERNAME
echo "$USERNAME:$USER_PASSWORD" | chpasswd
echo '%wheel ALL=(ALL) ALL' | EDITOR='tee -a' /usr/bin/visudo

# enable multilib
sed -i 's|\#Color|Color|g' /etc/pacman.conf
sed -i 's|\#\[multilib\]|\[multilib\]|g' /etc/pacman.conf
sed -i '94s|\#Include|Include|g' /etc/pacman.conf
pacman -Sy --noprogressbar


#--------------- Установка AUR-пакетов -------------------------
mkdir -p $USER_HOME/.cache/yay
mv /var/tmp/aur-cache/* $USER_HOME/.cache/yay
chown -R "$USERNAME:$USERNAME" $USER_HOME/.cache

mapfile -t ZST_FILES < <(find $USER_HOME/.cache/yay -type f -name '*.zst' ! -iname '*-debug*.zst' -print0 | xargs -0 -r -n1 echo)

pacman -U --needed --noconfirm --noprogressbar ${ZST_FILES[@]}


#--------------- Настройка системных приложений -------------------------
# lightdm
sed -i 's|#greeter-session=example-gtk-gnome|greeter-session=lightdm-slick-greeter|g' /etc/lightdm/lightdm.conf
sed -i 's|#greeter-setup-script=|greeter-setup-script=/usr/bin/numlockx on|g' /etc/lightdm/lightdm.conf # numlock on
# slick-greeter
echo "[Greeter]" > /etc/lightdm/slick-greeter.conf
echo "background=/usr/share/backgrounds/linuxmint-serena/capelli_ears_of_corn.jpg" >> /etc/lightdm/slick-greeter.conf
echo "theme-name=Sky-Mint-Y-Dark-Aqua" >> /etc/lightdm/slick-greeter.conf
echo "icon-theme-name=Newaita-reborn-mint-dark" >> /etc/lightdm/slick-greeter.conf
echo "cursor-theme-name=Empty-Butterfly-Yellow-vr1" >> /etc/lightdm/slick-greeter.conf
echo "clock-format=%H:%M     %e %B, %A" >> /etc/lightdm/slick-greeter.conf
echo "draw-user-backgrounds=false" >> /etc/lightdm/slick-greeter.conf
echo "draw-grid=true" >> /etc/lightdm/slick-greeter.conf
echo "activate-numlock=true" >> /etc/lightdm/slick-greeter.conf
echo "show-a11y=false" >> /etc/lightdm/slick-greeter.conf


# user autostart
cp /usr/share/applications/net.launchpad.plank.desktop $USER_HOME/.config/autostart/net.launchpad.plank.desktop
chown $USERNAME:$USERNAME $USER_HOME/.config/autostart/net.launchpad.plank.desktop
chmod +x $USER_HOME/.config/autostart/net.launchpad.plank.desktop
echo $'X-GNOME-Autostart-enabled=true\nHidden=false\nX-GNOME-Autostart-Delay=0' >> $USER_HOME/.config/autostart/net.launchpad.plank.desktop

cp /usr/share/applications/Yandex.Disk-indicator.desktop $USER_HOME/.config/autostart/Yandex.Disk-indicator.desktop
chown $USERNAME:$USERNAME $USER_HOME/.config/autostart/Yandex.Disk-indicator.desktop
chmod +x $USER_HOME/.config/autostart/Yandex.Disk-indicator.desktop
echo 'X-GNOME-Autostart-enabled=false' >> $USER_HOME/.config/autostart/Yandex.Disk-indicator.desktop

cp /usr/share/applications/mailspring.desktop $USER_HOME/.config/autostart/mailspring.desktop
chown $USERNAME:$USERNAME $USER_HOME/.config/autostart/mailspring.desktop
chmod +x $USER_HOME/.config/autostart/mailspring.desktop
sed -i "s|Exec=mailspring %U|Exec=mailspring --background|g" $USER_HOME/.config/autostart/mailspring.desktop

# cp /usr/share/applications/teams-for-linux.desktop $USER_HOME/.config/autostart/teams-for-linux.desktop
# chown $USERNAME:$USERNAME $USER_HOME/.config/autostart/teams-for-linux.desktop
# chmod +x $USER_HOME/.config/autostart/teams-for-linux.desktop
# sed -i "s|Exec=/opt/teams-for-linux/teams-for-linux %U|Exec=/opt/teams-for-linux/teams-for-linux --appIconType light --minimized true|g" $USER_HOME/.config/autostart/teams-for-linux.desktop
# echo 'X-GNOME-Autostart-enabled=false' >> $USER_HOME/.config/autostart/teams-for-linux.desktop

cp /etc/xdg/autostart/blueman.desktop $USER_HOME/.config/autostart/blueman.desktop
chown $USERNAME:$USERNAME $USER_HOME/.config/autostart/blueman.desktop
chmod +x $USER_HOME/.config/autostart/blueman.desktop
echo 'X-GNOME-Autostart-enabled=false' >> $USER_HOME/.config/autostart/blueman.desktop

echo "[Desktop Entry]
Type=Application
Exec=$USER_HOME/projects/skylab/scripts/tools/vscodium-backups
Icon=mintbackup
NoDisplay=false
Hidden=false
Name[ru_RU]=Резервирование текста VSCodium
Comment[ru_RU]=Резервирование текста VSCodium
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=0" > $USER_HOME/.config/autostart/vscodium-backups.desktop
chown $USERNAME:$USERNAME $USER_HOME/.config/autostart/vscodium-backups.desktop
chmod +x $USER_HOME/.config/autostart/vscodium-backups.desktop

rm -rf $USER_HOME/.config/autostart/cachyos-hello.desktop



# applications category
echo "[Desktop Entry]
Name=RemoteAndVMs
Comment=Remote connections and VMs
Name[ru]=Подключения и ВМ
Comment[ru]=Удалённые подключения и виртуальные машины
Icon=AppImage
Type=Directory" > /usr/share/desktop-directories/remote-and-vm.directory

mkdir --parents /etc/xdg/menus/applications-merged
echo "<Menu>
  <Name>Applications</Name>
  <Menu>
    <Name>RemoteAndVMs</Name>
    <Directory>remote-and-vm.directory</Directory>
    <Include>
      <Category>RemoteAndVMs</Category>
    </Include>
  </Menu>
</Menu>" > /etc/xdg/menus/applications-merged/remote-and-vm.menu


# sudo
echo "Defaults passwd_timeout=0" >> /etc/sudoers
echo "Defaults timestamp_timeout=15" >> /etc/sudoers

# all cores for aur builds
sed -i 's|#MAKEFLAGS="-j2"|MAKEFLAGS="-j$(nproc)"|g' /etc/makepkg.conf


# docker
mkdir -p /home/docker
mkdir -p /etc/docker
rm -rf /var/lib/docker
echo $'{
"data-root": "/home/docker",
"registry-mirrors": [
        "https://dockerhub.timeweb.cloud",
        "https://dh-mirror.gitverse.ru",
        "https://mirror.gcr.io",
        "https://daocloud.io",
        "https://c.163.com/",
        "https://registry.docker-cn.com",
        "https://huecker.io"
    ]
}' > /etc/docker/daemon.json

echo "options overlay metacopy=off redirect_dir=off" > /etc/modprobe.d/disable-overlay-redirect-dir.conf


rm -rf /usr/share/backgrounds/gnome/
rm -f /usr/share/gnome-background-properties/adwaita.xml
rm -f /usr/share/gnome-background-properties/amber.xml
rm -f /usr/share/gnome-background-properties/blobs.xml
rm -f /usr/share/gnome-background-properties/drool.xml
rm -f /usr/share/gnome-background-properties/fold.xml
rm -f /usr/share/gnome-background-properties/geometrics.xml
rm -f /usr/share/gnome-background-properties/glass-chip.xml
rm -f /usr/share/gnome-background-properties/lcd-rainbow.xml
rm -f /usr/share/gnome-background-properties/lcd.xml
rm -f /usr/share/gnome-background-properties/map.xml
rm -f /usr/share/gnome-background-properties/mollnar.xml
rm -f /usr/share/gnome-background-properties/morphogenesis.xml
rm -f /usr/share/gnome-background-properties/neogeo.xml
rm -f /usr/share/gnome-background-properties/pills.xml
rm -f /usr/share/gnome-background-properties/pixels.xml
rm -f /usr/share/gnome-background-properties/pride.xml
rm -f /usr/share/gnome-background-properties/progress.xml
rm -f /usr/share/gnome-background-properties/ring.xml
rm -f /usr/share/gnome-background-properties/sheet.xml
rm -f /usr/share/gnome-background-properties/swoosh.xml
rm -f /usr/share/gnome-background-properties/symbolic-soup.xml
rm -f /usr/share/gnome-background-properties/symbolic.xml
rm -f /usr/share/gnome-background-properties/tarka.xml
rm -f /usr/share/gnome-background-properties/vnc.xml
rm -f /usr/share/gnome-background-properties/balls.xml
rm -f /usr/share/gnome-background-properties/blendpills.xml
rm -f /usr/share/gnome-background-properties/curvy.xml
rm -f /usr/share/gnome-background-properties/dithered-sun.xml
rm -f /usr/share/gnome-background-properties/pixel-pusher.xml
rm -f /usr/share/gnome-background-properties/tarkov-pills.xml
rm -f /usr/share/gnome-background-properties/tubes.xml



#--------------- Настройка пользовательских приложений -------------
mv /root/install-on-user $USER_HOME/install-on-user
mv /root/user-first-login $USER_HOME/user-first-login
chown "$USERNAME:$USERNAME" $USER_HOME/user-first-login
mv /root/user-prefs.dconf $USER_HOME/user-prefs.dconf
chown "$USERNAME:$USERNAME" $USER_HOME/user-prefs.dconf

sudo -u $USERNAME $USER_HOME/install-on-user

rm -f $USER_HOME/install-on-user
rm -f $USER_HOME/user-prefs.dconf



#--------------- Завершение -------------------------
systemctl enable NetworkManager
systemctl enable qemu-guest-agent
systemctl enable lightdm

DISK=/dev/sda
grub-install --target=i386-pc --recheck $DISK
grub-mkconfig -o /boot/grub/grub.cfg
