#!/usr/bin/env bash

sleep 5

#--------------- Setup desktop -------------
sed -i 's|"%A, %B %e, %H:%M"|"%H:%M     %e %B, %A"|g' $HOME/.config/cinnamon/spices/calendar@cinnamon.org/12.json
sed -i '25s|false|true|g' $HOME/.config/cinnamon/spices/calendar@cinnamon.org/12.json
sed -i '188s|true|false|g' $HOME/.config/cinnamon/spices/menu@cinnamon.org/0.json # show-desktop.value
sed -i '200s|true|false|g' $HOME/.config/cinnamon/spices/menu@cinnamon.org/0.json # show-downloads.value
sed -i '224s|true|false|g' $HOME/.config/cinnamon/spices/menu@cinnamon.org/0.json # show-bookmarks.value
sed -i '255s|24|32|g' $HOME/.config/cinnamon/spices/menu@cinnamon.org/0.json # sidebar-icon-size.value
sed -i '331s|665|730|g' $HOME/.config/cinnamon/spices/menu@cinnamon.org/0.json # popup-width.value
sed -i '336s|425|625|g' $HOME/.config/cinnamon/spices/menu@cinnamon.org/0.json # popup-height.value
sed -i 's|"value": "visual"|"value": "buttons"|g' $HOME/.config/cinnamon/spices/workspace-switcher@cinnamon.org/17.json
sed -i '14d' $HOME/.config/cinnamon/spices/panel-launchers@cinnamon.org/13.json
sed -i '14d' $HOME/.config/cinnamon/spices/panel-launchers@cinnamon.org/13.json
sed -i '14s|"nemo.desktop"|"org.gnome.SystemMonitor.desktop",\n"org.gnome.Terminal.desktop",\n"org.gnome.Calculator.desktop",\n"org.gnome.Screenshot.desktop",\n"deluge.desktop",\n"org.gnome.meld.desktop",\n"postman.desktop",\n"bitwarden.desktop",\n"codium.desktop",\n"video-collector-client.desktop"|g' $HOME/.config/cinnamon/spices/panel-launchers@cinnamon.org/13.json

echo '{"width":{"type":"scale","default":10,"min":2,"max":400,"step":1,"value":7},"__md5__":"ce7d0d70f40859fec53e8c70cde93a17"}
' > $HOME/.config/cinnamon/spices/spacer@cinnamon.org/23.json
cp $HOME/.config/cinnamon/spices/spacer@cinnamon.org/23.json $HOME/.config/cinnamon/spices/spacer@cinnamon.org/24.json
cp $HOME/.config/cinnamon/spices/spacer@cinnamon.org/23.json $HOME/.config/cinnamon/spices/spacer@cinnamon.org/25.json
cp $HOME/.config/cinnamon/spices/spacer@cinnamon.org/23.json $HOME/.config/cinnamon/spices/spacer@cinnamon.org/26.json
cp $HOME/.config/cinnamon/spices/spacer@cinnamon.org/23.json $HOME/.config/cinnamon/spices/spacer@cinnamon.org/27.json
cp $HOME/.config/cinnamon/spices/spacer@cinnamon.org/23.json $HOME/.config/cinnamon/spices/spacer@cinnamon.org/34.json

sed -i 's|"value":7|"value":20|g' $HOME/.config/cinnamon/spices/spacer@cinnamon.org/27.json
cp $HOME/.config/cinnamon/spices/spacer@cinnamon.org/27.json $HOME/.config/cinnamon/spices/spacer@cinnamon.org/32.json
cp $HOME/.config/cinnamon/spices/spacer@cinnamon.org/27.json $HOME/.config/cinnamon/spices/spacer@cinnamon.org/33.json

sed -i 's|nemo-icon-view-auto-layout=true|nemo-icon-view-auto-layout=false|g' $HOME/.config/nemo/desktop-metadata



#--------------- Setup apps -------------
plank >> /dev/null . &
sleep 3
pkill plank
rm -f $HOME/.config/plank/dock1/launchers/*

echo $'[PlankDockItemPreferences]\nLauncher=docklet://clock\n\n[DockyClockPreferences]\n#If the clock shows 24hr time (when showing digital and in the hover).\nShowMilitary=false\n#If the clock shows a digital clock (true) or an analog clock (false).\nShowDigital=false\n#If the clock shows the date in digital mode.\nShowDate=false' > $HOME/.config/plank/dock1/launchers/clock.dockitem
echo $'[PlankDockItemPreferences]\nLauncher=docklet://clippy\n\n[DockyClippyPreferences]\n#How many recent clipboard entries to keep.\nMaxEntries=15\n#If it should track the primary (mouse selection) clipboard.\nTrackMouseSelections=false' > $HOME/.config/plank/dock1/launchers/clippy.dockitem
echo $'[PlankDockItemPreferences]\nLauncher=file:///usr/share/applications/yandex-browser.desktop' > $HOME/.config/plank/dock1/launchers/yandex-browser.dockitem
echo $'[PlankDockItemPreferences]\nLauncher=file:///usr/share/applications/nemo.desktop' > $HOME/.config/plank/dock1/launchers/nemo.dockitem
echo $'[PlankDockItemPreferences]\nLauncher=file:///usr/share/applications/jetbrains-idea.desktop' > $HOME/.config/plank/dock1/launchers/jetbrains-idea.dockitem
echo $'[PlankDockItemPreferences]\nLauncher=file:///usr/share/applications/GitKraken.desktop' > $HOME/.config/plank/dock1/launchers/GitKraken.dockitem

gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ dock-items "['clock.dockitem', 'clippy.dockitem', 'yandex-browser.dockitem', 'nemo.dockitem', 'jetbrains-idea.dockitem', 'GitKraken.dockitem']"

plank &


# folders icons
gio set $HOME/Фотографии metadata::custom-icon file:///usr/share/icons/Newaita-reborn-pop-os-dark/places/64/folder-photos.svg
gio set "$HOME/Семейные древа" metadata::custom-icon file:///usr/share/icons/Newaita-reborn-pop-os-dark/places/64/folder-activities.svg
gio set $HOME/Архив metadata::custom-icon file:///usr/share/icons/Newaita-reborn-pop-os-dark/places/64/folder-tar.svg
gio set $HOME/projects metadata::custom-icon file:///usr/share/icons/Newaita-reborn-dracula-dark/places/64/folder-templates.svg
gio set $HOME/yandex.disk metadata::custom-icon file:///usr/share/icons/Newaita-reborn-deep-purple-dark/places/64/folder-yandex-disk.svg
gio set $HOME/mega.sync metadata::custom-icon file:///usr/share/icons/Newaita-reborn/places/24/folder-cloud.svg
gio set $HOME/.config metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-gray.svg
gio set $HOME/.local metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-brown.svg
gio set $HOME/.local/backups metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-gray.svg
gio set $HOME/skylab metadata::custom-icon file:///usr/share/icons/Newaita-reborn-gray-dark/places/64/folder-favorites.svg

gio set $HOME/projects/kodepix metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-green.svg
gio set $HOME/projects/demo metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-light-brown.svg
gio set $HOME/projects/skylab/bookstore metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-light-blue.svg
gio set $HOME/projects/skylab metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-purple.svg
gio set $HOME/projects/skylab/scripts metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-purple.svg
gio set $HOME/projects/skylab/tools metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-gray.svg
gio set $HOME/projects/skylab/video-collector metadata::custom-icon file:///usr/share/icons/Newaita-reborn-ubuntu-dark/places/64/folder-mojito.svg



rm -f $HOME/.config/autostart/user-first-login.desktop
rm -f $HOME/user-first-login

cinnamon --replace &
