events {
    multi_accept on;
    worker_connections 1024;
}

http {
    client_max_body_size 0;

    server {
        listen 80;
        server_name bookstore.local;

        location / {
            proxy_pass http://localhost:8094/;
        }
    }
}
