[Greeter]
background=/usr/share/backgrounds/linuxmint-serena/capelli_ears_of_corn.jpg
theme-name=Sky-Mint-Y-Dark-Aqua
icon-theme-name=Newaita-reborn-mint-dark
cursor-theme-name=Empty-Butterfly-Yellow-vr1
clock-format=%H:%M     %e %B, %A
draw-user-backgrounds=false
draw-grid=true
activate-numlock=true
show-a11y=false
