## system
gnome-terminal-transparency
plank-reloaded
newaita-reborn-icons-git
mint-backgrounds-rosa
mint-backgrounds-serena
mint-backgrounds-vanessa
popsicle-bin
ocs-url
qjournalctl
icaclient # for gpb; manual linuxx64-gcc-8-26.04.0.105.tar.gz
cryptopro-csp-k1 # for gpb; manual linux-amd64.tgz
fish-pure-prompt
ltunify # m590 radio pair


## development
intellij-idea-ultimate-edition # manual ideaIU-2025.3.4.tar.gz
gitkraken # manual gitkraken-amd64.tar.gz
postman-bin
debtap
schemaspy # sql schema
cambalache # gtk4 ui builder


## office
vscodium-bin
onlyoffice-bin
goocanvas2 # for gramps
max-bin
telegram-desktop-bin
google-earth-pro
mailspring-bin
yandex-disk-indicator # run yandex-disk token for auth
# megasync-bin blocked
yandex-browser


## media
flacon
simplescreenrecorder
# tiny-media-manager blocked # create nfo (for home video)
# kodi-nfo-generator
video-collector-client
