## system
gnome-terminal-transparency
plank-reloaded
newaita-reborn-icons-git
mint-backgrounds-rosa
mint-backgrounds-serena
# mint-backgrounds-uma
mint-backgrounds-vanessa
# popsicle-bin t/o
ocs-url
qjournalctl
# libva-mesa-driver (failed)
# libva-utils err
#webkit2gtk w/o icaclient # for gpb
# cryptopro-csp-k1 err # for gpb


## development
# postman-bin blocked
debtap
schemaspy # sql schema


## office
vscodium-bin
onlyoffice-bin
goocanvas2 # for gramps
max-bin
google-earth-pro
electron33-bin # for mailspring-bin
mailspring-bin
yandex-disk-indicator # run yandex-disk token for auth
# megasync-bin blocked
yandex-browser
vkteams-bin # for gpb


## media
flacon
simplescreenrecorder # simplescreenrecorder-bin: 404
# tiny-media-manager blocked # create nfo (for home video)
video-collector-client
