#!/usr/bin/env bash

pacman-cache() {
    mkdir -p /targetfs/var/cache/pacman/pkg
    mv /targetfs/var/cache/pacman/pkg/*.{zst,zst.sig} /var/cache/pacman/pkg

    mapfile -t PACMAN_PACKAGES_ARR < <(sed -e 's/#.*//' -e 's/[[:space:]]*$//' -e '/^[[:space:]]*$/d' /root/pacman-packages.conf)

    rate-mirrors --allow-root --save /etc/pacman.d/mirrorlist arch

    PACMAN_PACKAGES=$(sed 's/#.*//' /root/pacman-packages.conf | sed '/^[[:space:]]*$/d' | xargs)
    pacman -S --needed --noconfirm --noprogressbar $PACMAN_PACKAGES
}

aur-cache() {
    #--------------- Временный пользователь -------------------------
    useradd -m -s /bin/bash -G wheel aur_builder_user
    mkdir -p /etc/sudoers.d
    echo "aur_builder_user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/aur_builder_user && chmod 440 /etc/sudoers.d/aur_builder_user

    mkdir -p /targetfs/var/tmp/aur-cache
    mkdir -p /home/aur_builder_user/.cache/yay
    mv /targetfs/var/tmp/aur-cache/* /home/aur_builder_user/.cache/yay
    chown -R aur_builder_user:aur_builder_user /home/aur_builder_user

    #--------------- Установка --------------------------------------
    sudo -u aur_builder_user bash -lc "
      git clone --quiet https://aur.archlinux.org/yay-bin.git ~/.cache/yay/yay-bin
      cd ~/.cache/yay/yay-bin
      makepkg --syncdeps --install --noconfirm --noprogressbar"

    mapfile -t PACKAGES_ARR < <(sed -e 's/#.*//' -e 's/[[:space:]]*$//' -e '/^[[:space:]]*$/d' /root/aur-packages.conf)

    for pkg in "${PACKAGES_ARR[@]}"; do
      sudo -u aur_builder_user bash -lc "yay -Sq --needed --noconfirm --noprogressbar $pkg"
    done

    rm -rf /home/aur_builder_user/.cache/yay/**/src/

    sudo -u aur_builder_user bash -lc "
      git clone --quiet https://aur.archlinux.org/intellij-idea-ultimate-edition.git ~/.cache/yay/intellij-idea-ultimate-edition
      cd ~/.cache/yay/intellij-idea-ultimate-edition
      sed -i 's|download.jetbrains.com|download-cdn.jetbrains.com|g' ./PKGBUILD
      git config user.name 'you@example.com'
      git config user.email 'you@example.com'
      git commit -a -m 'use cdn'
      yay -Sq --needed --noconfirm --noprogressbar intellij-idea-ultimate-edition"

    rm -rf /home/aur_builder_user/.cache/yay/**/*.tar.gz
    rm -rf /home/aur_builder_user/.cache/yay/**/*.zip
    rm -rf /home/aur_builder_user/.cache/yay/**/*.deb
    rm -rf /home/aur_builder_user/.cache/yay/**/*.rpm
    rm -rf /home/aur_builder_user/.cache/yay/**/*-debug*.zst
    mv /home/aur_builder_user/.cache/yay/* /targetfs/var/tmp/aur-cache
}

custom() {
    rm -rf /targetfs/opt/jetbra
    rm -rf /targetfs/etc
    rm -rf /targetfs/usr/share/*
    mkdir -p /targetfs/opt/jetbra
    mkdir -p /targetfs/etc
    mkdir -p /targetfs/usr/share/themes
    mkdir -p /targetfs/usr/share/plank/themes
    mkdir -p /targetfs/usr/share/icons
    mkdir -p /targetfs/usr/share/grub/themes

    curl -sL https://github.com/dmitry-oshurkov/files/releases/download/1/jtbr.tar.gz | tar -xz -C /targetfs/opt
    curl -sLO --output-dir /targetfs/var/tmp https://open-vsx.org/api/MS-CEINTL/vscode-language-pack-ru/1.121.0/file/MS-CEINTL.vscode-language-pack-ru-1.121.0.vsix
    curl -sL -o /targetfs/etc/hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

    curl -sL https://github.com/dmitry-oshurkov/sky-arc-theme/releases/download/22.1/Sky-Arc-Darker.tar.gz | tar -xz -C /targetfs/usr/share/themes/
    curl -sL https://github.com/dmitry-oshurkov/sky-arc-theme/releases/download/22.1/Sky-Arc-Darker-Plank.tar.gz | tar -xz -C /targetfs/usr/share/plank/themes/
    curl -sL https://github.com/dmitry-oshurkov/mint-themes/releases/download/22.1/themes.tar.gz | tar -xz -C /targetfs/usr/share/themes/
    curl -sL https://github.com/dmitry-oshurkov/files/releases/download/1/Empty-Butterfly-Yellow-vr1.tar.gz | tar -xz -C /targetfs/usr/share/icons/
    curl -sL https://github.com/dmitry-oshurkov/files/releases/download/1/skyos.tar.gz | tar -xz -C /targetfs/usr/share/grub/themes
}

pacman-cache
aur-cache
custom

mv /var/cache/pacman/pkg/*.{zst,zst.sig} /targetfs/var/cache/pacman/pkg
chmod -R a+w /targetfs
