# system
base
linux
linux-firmware
networkmanager
mc
sudo
base-devel
git
rate-mirrors
grub
qemu-guest-agent
spice-vdagent
lightdm
lightdm-slick-greeter
cinnamon
# cinnamon-translations
gnome-system-monitor
mc
nemo-fileroller
nemo-compare
nemo-emblems
gnome-calculator
gnome-disk-utility
gucharmap
sshpass
gparted
remmina
freerdp
strongswan
blueman # for manual enable mouse
nginx-mainline
gvfs # for nemo webdav
gvfs-smb # for nemo smb
gvfs-dnssd # for nemo webdav
gvfs-mtp # for android connect
numlockx
dconf-editor
baobab
gprename
7zip
nvtop
gnome-screenshot
qemu
virt-viewer
wine
networkmanager-openconnect # for it1
#webkit2gtk-4.1 anavail icaclient # for gpb
veracrypt
# fish

## development
docker
docker-buildx
docker-compose
kubectl
jdk21-openjdk
yarn # for gitkraken-patch
# glade # gtk editor
# meson # build gtk themes
# sassc # build gtk themes
# inkscape # build gtk themes
## nvidia
# nvidia-open
# nvidia-container-toolkit
# cuda
# cudnn
# opencv # for c2m facesdk

## office
xviewer
bitwarden
osm-gps-map # for gramps
gramps
evince # document viewer

## media
mediainfo-gui
mkvtoolnix-gui
smplayer
smplayer-skins
smplayer-themes
avidemux-qt
lollypop
gimp
deluge-gtk
picard
kid3-qt
sox # for flacon (ape)
mac # for flacon (ape)
foliate
shotwell
perl-image-exiftool
